spring:
   profiles:
     active: local
   application:
     name: unlimits_integration
   main:
     allow-bean-definition-overriding: true
openai:
   model: gpt-3.5-turbo
   api:
     key: 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
     urlmodels: https://api.openai.com/v1/models
     urlchat: https://api.openai.com/v1/chat/completions
     urlaudio: https://api.openai.com/v1/audio
     urlimages: https://api.openai.com/v1/images

springdoc:
   swagger-ui:
      path: /api/swagger-ui.html
server: 
  port: 7777
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
    
