spring:
   profiles:
     active: local
   application:
     name: unlimits_integration
   main:
     allow-bean-definition-overriding: true
openai:
   model: gpt-3.5-turbo
   api:
     key: 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
     urlmodels: https://api.openai.com/v1/models
     urlchat: https://api.openai.com/v1/chat/completions
     urlaudio: https://api.openai.com/v1/audio
     urlimages: https://api.openai.com/v1/images
     
google:
   api:
      key: AIzaSyDNnzAkd3sd_f7NH_kStnEK_MB5VUSOr2w
      driveId: 12CCvmzIWirEGI5nKuRmOhI_KZnb-gSUA
pexels:
   api:
      key: PscnQK1xzBeUece4hZCnRPajD3eAL03orDj4KEiWYozfslb0uSf1LVzN
      urlimages: https://api.pexels.com/v1/search?query=nature&per_page=100
springdoc:
   swagger-ui:
      path: /api/swagger-ui.html
server: 
  port: 4444
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
    
