server: 
  port: 4444
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true

spring:
   profiles:
     active: local
   application:
     name: unlimits_integration
   main:
     allow-bean-definition-overriding: true
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://51.79.159.7:1111/eureka/
openai:
   model: gpt-4o
   api:
     key: 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
     urlmodels: https://api.openai.com/v1/models
     urlchat: https://api.openai.com/v1/chat/completions
     urlaudio: https://api.openai.com/v1/audio
     urlimages: https://api.openai.com/v1/images
     
google:
   api:
      key: AIzaSyDNnzAkd3sd_f7NH_kStnEK_MB5VUSOr2w
      driveId: 12CCvmzIWirEGI5nKuRmOhI_KZnb-gSUA
pexels:
   user: sajith@unlimits.ai
   password: unlimits2024
   api:
      key: shZFoL0bXoM1fPRCtZ7SFM6adEu3EtDkmQWK2QvbytZ6khWL5ph5qfqZ
      urlimages: https://api.pexels.com/v1/search
springdoc:
   swagger-ui:
      path: /api/swagger-ui.html
openapi:
  service:
      url: http://51.79.159.7:8080/integration
content:
   api:
     url: http://51.79.159.7:8080/content